FluffyCRM/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FluffyCRM.Models
{
    public enum ticketStatus {
        NONE=0,
        NEW=1,
        ASSIGNED=2,
        STARTED=4,
        HOLD=8,
        COMPLETE=16,
        CLOSED=32
        
    }

    public class Ticket
    {
        [Key]
        [DisplayName("Ticket Number")]
        public int TicketId { get; set; }

        [DisplayName("Subject")]
        [StringLength(255)]
        public string Subject { get; set; }

        [DisplayName("Category")]
        public int? CategoryId { get; set; }

        [DisplayName("Created")]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime? CreateDate { get; set; }

        [DisplayName("Description")]
        [StringLength(8000)]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [DefaultValue(0)]
        public ticketStatus? Status { get; set; }

        [DefaultValue(false)]
        public bool DeleteInd { get; set; }

        [DisplayName("Customer")]
        public int? ClientId { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("Start Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? StartDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("Date Completed")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? CompletedDate { get; set; }

        [DisplayName("Due Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? DueDate { get; set; }

        public DateTime? LocalTime { get; set; }


        [StringLength(128)]
        public string CreatedBy { get; set; }

    }

   
}

FluffyCRM/Controllers/TicketsController.cs
using System;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using FluffyCRM.Models;
using FluffyCRM.ViewModels;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Collections.Generic;
using FluffyCRM.DAL;
using PagedList;

namespace FluffyCRM.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private DataRepository _repos = new DataRepository();




        // GET: Tickets

        
        [Authorize(Roles = "Admin,Client,Staff")]
        public ActionResult Index(string searchString = "",  string sortOption = "", int page = 1, string srchclient = "", string srchcreated = "" )
        {
            int pageSize = 10;
            var userId = User.Identity.GetUserId();


            ViewBag.CurrentFilter = searchString;
            if (sortOption == null) sortOption = "name_acs";
            ViewBag.sortOption = sortOption;
            ViewBag.CurrentUser = userId;

            IEnumerable<TicketList> lst = new List<TicketList>();

            if ((User.IsInRole("Staff") || User.IsInRole("Admin")))
            {
                lst = _repos.GetTicketList("");
            }
            else
            {
                lst = _repos.GetTicketList(userId);
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                lst = lst.Where(s => s.Subject.Contains(searchString) || s.Description.Contains(searchString));
            }
            //switch (sortOption)
            //{
            //    case "name_acs":
            //        lst = lst.OrderBy(p => p.Name);
            //        ViewBag.sortOption = "name_desc";
            //        break;
            //    case "name_desc":
            //        lst = lst.OrderByDescending(p => p.Name);
            //        ViewBag.sortOption = "name_asc";
            //        break;

            //    default:
            //        lst = lst.OrderBy(p => p.LocalTime);
            //        ViewBag.sortOption = "name_desc";
            //        break;

            //}

            return Request.IsAjaxRequest()
               ? (ActionResult)PartialView("Index", lst.ToPagedList(page, pageSize))
               : View(lst.ToPagedList(page, pageSize));


           
 
          //  return View(lst);
        }

        // GET: Tickets/Details/5
        [Authorize(Roles = "Admin,Client,Staff")]
        public async Task<ActionResult> Details(int? id)
        {
            ViewBag.CurrentUser = User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = await db.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // GET: Tickets/Create
        [Authorize(Roles = "Admin,Client,Staff")]
        public ActionResult Create()
        {
            ViewBag.TicketCategories = new SelectList(_repos.GetCategoryList(FLCatType.Ticket), "id", "Name", null);
            ViewBag.CustList = new SelectList(_repos.GetClientListAll(), "ClientId", "CompanyName", null);
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Client,Staff")]
        public async Task<ActionResult> Create([Bind(Include = "Subject,CategoryId,Description,ClientId,DueDate,CreatedBy,Status,LocalTime")] Ticket ticket)
        {
            DateTime now = new DateTime();
            now = DateTime.Now;
            ticket.CreatedBy = User.Identity.GetUserId();
            ticket.Status = ticketStatus.NEW;
            ticket.LocalTime = now;
            IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);

            if (ModelState.IsValid)
            {
                db.Tickets.Add(ticket);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        [Authorize(Roles = "Admin,Client,Staff")]
        public ActionResult AddClientTicket()
        {
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Client,Staff")]
        public async Task<ActionResult> AddClientTicket([Bind(Include = "Subject,Description,ClientId")] ClientTicket clientTicket)
        {
            DateTime now = new DateTime();
            now = DateTime.Now;

            Ticket ticket = new Ticket();
            ticket.LocalTime = now;

            ticket.CategoryId = 0;

            ticket.Subject = clientTicket.Subject;
            ticket.Description = clientTicket.Description;


            ticket.Status = ticketStatus.NEW;
            ticket.CreatedBy = User.Identity.GetUserId();
        
            ticket.ClientId = _repos.GetClientByUID(ticket.CreatedBy);

            IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                db.Tickets.Add(ticket);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
           }

            return View(clientTicket);
        }

        // GET: Tickets/Edit/5
        [Authorize(Roles = "Admin,Client,Staff")]
        public async Task<ActionResult> Edit(int? id)
        {
            var userID =  User.Identity.GetUserId();
            ViewBag.CurrentUser = userID;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = await db.Tickets.FindAsync(id);

            if (ticket == null)
            {
                return RedirectToAction("Index");
            }

            if (!(User.IsInRole("Admin"))) {
                if (userID != ticket.CreatedBy) return RedirectToAction("Details", new { id = id });
            }
            ViewBag.TicketCategories = new SelectList(_repos.GetCategoryList(FLCatType.Ticket), "id", "Name", null);
            ViewBag.CustList = new SelectList(_repos.GetClientListAll(), "ClientId", "CompanyName", null);

            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Client,Staff")]
        public ActionResult Edit([Bind(Include = "TicketId,Subject,CategoryId,Description,Status,ClientId,StartDate,CompletedDate,DueDate")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ticket).State = EntityState.Modified;
                //  db.SaveChanges();
                if (User.IsInRole("Admin") || User.IsInRole("Staff"))
                {
                    _repos.UpdateTicket(ticket);
                }
                else {
                    _repos.UpdateClientTicket(ticket);
                }
               
                return RedirectToAction("Index");
            }
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = await db.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Ticket ticket = await db.Tickets.FindAsync(id);
            db.Tickets.Remove(ticket);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FluffyCRM/Views/Tickets/AddClientTicket.cshtml
@model FluffyCRM.ViewModels.ClientTicket

@{
    ViewBag.Title = "Add Support Ticket";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ticket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>
       
       

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

      
       

        

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FluffyCRM/Views/Tickets/Create.cshtml
@model FluffyCRM.Models.Ticket

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ticket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.DropDownListFor(m => m.CategoryId, (IEnumerable<SelectListItem>)ViewBag.TicketCategories, "--Select One--")
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

     

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

 


        <div class="form-group">
            @Html.LabelFor(model => model.ClientId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.DropDownListFor(m => m.ClientId, (IEnumerable<SelectListItem>)ViewBag.CustList, "--Select One--")


                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

  

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FluffyCRM/Views/Tickets/Delete.cshtml
@model FluffyCRM.Models.Ticket

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeleteInd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeleteInd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompletedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompletedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FluffyCRM/Views/Tickets/Details.cshtml
@model FluffyCRM.Models.Ticket

@{
    ViewBag.Title = "Support Ticket Details";
}

<div>

    <div class="container-fluid noteform">
        <div class="panel col-med-12 col-med-12 col-lg-12 col-xs-12 panel-primary">
            <!-- HEADING  -->
            <div class="panel-heading color-p-1">
                <div class="col-sm-6 col-med-4 col-lg-4  col-xs-12">
                    @(ViewBag.Title)
                   
                </div>
                <div class="col-sm-6 col-med-4 col-lg-4  col-xs-12">
                    <span class="smalllabel">@Html.DisplayNameFor(model => model.TicketId)</span><br />
                    @Html.DisplayFor(model => model.TicketId)
                    <br />
                </div>
                <div class="col-sm-6 col-med-4 col-lg-4  col-xs-12">
                    &nbsp;<div class="text-right btn btn-info">@Html.ActionLink("Back to listing", "Index")</div>
                    <br />
                </div>
                <br /><br />
            </div>
           
            <!-- END HEADING  -->
            <div class="col-sm-6 col-med-4 col-lg-4  col-xs-12  ">
                <span class="smalllabel">@Html.DisplayNameFor(model => model.Subject)</span><br />
                @Html.DisplayFor(model => model.Subject)
            </div>

            <div class="col-sm-6 col-med-4 col-lg-4  col-xs-12  ">
                <span class="smalllabel">@Html.DisplayNameFor(model => model.CreateDate)</span><br />
                @Html.DisplayFor(model => model.CreateDate)<br />

                <!-- Staff and admin can see dates -->
                @if (User.IsInRole("Admin") || User.IsInRole("Staff"))
                {
                <span class="smalllabel">@Html.DisplayNameFor(model => model.StartDate)</span><br />
                @Html.DisplayFor(model => model.StartDate)<br />

                <span class="smalllabel">@Html.DisplayNameFor(model => model.DueDate)</span><br />
                @Html.DisplayFor(model => model.DueDate)<br />

                <span class="smalllabel">@Html.DisplayNameFor(model => model.CompletedDate)</span><br />
                @Html.DisplayFor(model => model.CompletedDate)<br />
                }
                <!-- //TODO: need closed indicator --> 

            </div>

            <div class="col-sm-6 col-med-4 col-lg-4  col-xs-12  ">
                <span class="smalllabel">@Html.DisplayNameFor(model => model.Status)</span><br />
                @Html.DisplayFor(model => model.Status)<br />

                <span class="smalllabel">@Html.DisplayNameFor(model => model.CategoryId)</span><br />
                @Html.DisplayFor(model => model.CategoryId)<br />

            </div>

            <div class="col-sm-12 col-med-12 col-lg-12  col-xs-12  noteform">
                <span class="smalllabel">@Html.DisplayNameFor(model => model.Description)</span><br />
                @Html.DisplayFor(model => model.Description)<br />
            </div>

        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.TicketId }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
</div>


    
  <div class="btn btn-primary">
    @Html.ActionLink("Add",  "Create" , "TicketComments", new { id = Model.TicketId },null)</div> 
<div>@Html.Action("Index", "TicketComments", new { id = Model.TicketId })</div>

FluffyCRM/Views/Tickets/Edit.cshtml
@model FluffyCRM.Models.Ticket

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>



@if (Model.CreatedBy == ViewBag.CurrentUser || (User.IsInRole("Admin")))
{
<span>&nbsp;</span>
using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
    
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <h4>Ticket#:&nbsp;&nbsp;@Html.DisplayFor(model => model.TicketId)</h4><hr />
       
        <div class="form-group">
            @Html.HiddenFor(model => model.TicketId)
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(m => m.CategoryId, (IEnumerable<SelectListItem>)ViewBag.TicketCategories, "--Select One--")
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (User.IsInRole("Admin"))
        {
        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeleteInd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DeleteInd)
                    @Html.ValidationMessageFor(model => model.DeleteInd, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ClientId, (IEnumerable<SelectListItem>)ViewBag.CustList, "--Select One--")
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompletedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompletedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompletedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

} else {
<div class="well alert-warning" >You may only edit text for you own tickets. You can copy and pase the content into another ticket if necessary.  </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FluffyCRM/Views/Tickets/Index.cshtml
@model PagedList.IPagedList<FluffyCRM.ViewModels.TicketList>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Ticket Listing";
}

<h6>@ViewBag.Title</h6>


@using (Html.BeginForm("Index", "Tickets", FormMethod.Get))
{
    <p>
        Search: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)

        <input type="submit" value="Search" />
    </p>
}
<p>
    @if (User.IsInRole("Staff")|| User.IsInRole("Admin"))
    {
        @Html.ActionLink("Create New", "Create")
    }
    else if (User.IsInRole("Client"))
    {
        @Html.ActionLink("Create New", "AddClientTicket")
    }
    else
    {
       
    }
</p>


<div class="table">
    <div class="row bottomborder">
        <div class="col-lg-1">Ticket#</div>
        <div class="col-lg-1">
           Subject
        </div>
        
        <div class="col-lg-1">
           Create Date
        </div>
       <div class="col-lg-3">
            Short Desc
        </div>
        <div class="col-lg-1">
           Status
        </div>
        <di class="col-lg-1">
           Company Name
        </di>
        <div class="col-lg-1">
            Full Name
        </div>

 @if (User.IsInRole("Admin") || User.IsInRole("Staff"))
 {

           <div class="col-lg-1">
           Start Date<br /> Due Date<br /> Completed Date
        </div>
       
        <div class="col-lg-1">
            Category
        </div>
 }
        <div class="col-lg-1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
    </div>

@foreach (var item in Model) {
    <div class="row maccordion  expandtext bottomborder "  >
        
        <div  class="col-lg-1 ">@Html.DisplayFor(modelItem => item.TicketId)</div>
        
        <div  class="col-lg-1">
            @Html.DisplayFor(modelItem => item.Subject)
        </div>
      
        <div  class="col-lg-1 smalllabel">
            @Html.DisplayFor(modelItem => item.CreateDate)
        </div>
        
        <div  class="col-lg-3">
            @Html.DisplayFor(modelItem => item.Description)
        </div>
        
        <div  class="col-lg-1">
            @Html.DisplayFor(modelItem => item.Status)
        </div>
        
        <div  class="col-lg-1 smalllabel">
            @Html.DisplayFor(modelItem => item.CompanyName)
        </div>
        
        <div  class="col-lg-1 smalllabel">
            @Html.DisplayFor(modelItem => item.FullName)
        </div>
    @if (User.IsInRole("Admin") || User.IsInRole("Staff"))
    {
        <div  class="col-lg-1 smalllabel">
            @Html.DisplayFor(modelItem => item.StartDate)
            <br />
            @Html.DisplayFor(modelItem => item.DueDate)
            <br />
            @Html.DisplayFor(modelItem => item.CompletedDate) 
        </div>
        
        <div  class="col-lg-1">
            @Html.DisplayFor(modelItem => item.Category)
        </div>
        
        <div  class="col-lg-1">
            @Html.ActionLink(" ", "Edit", new { id = item.TicketId }, new { @class = "glyphicon glyphicon-edit" }) &nbsp;
            @Html.ActionLink(" ", "Details", new { id = item.TicketId }, new { @class = "glyphicon glyphicon-file" })  &nbsp;
            @Html.ActionLink(" ", "Delete", new { id = item.TicketId }, new { @class = "glyphicon glyphicon-remove" })
        </div>

    }
    else if (User.IsInRole("Client"))
    {
        <div>

            @Html.ActionLink(" ", "Details", new { id = item.TicketId }, new { @class = "glyphicon glyphicon-file" })  &nbsp;
        </div>

    }
    </div>
}

</div>
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))